### ISSUE TITLE
Wrong Hierachy of Credit Class?

### ISSUE THREAD

**Issue by simonfranz** [DraperStudio/Laravel-Rewardable#4]
Hi,
I'm wondering about the inheritance of https://github.com/DraperStudio/Laravel-Rewardable/blob/master/src/Models/Credit.php

It clearly inherits from Model, but 
`use DraperStudio\Database\Models\Model;`
isn't in the package, maybe it's ment to be
`use Illuminate\Database\Eloquent\Model;`

By now I'm also searching for the PresentableTrait (`use DraperStudio\Database\Traits\Models\PresentableTrait;`),
but wasn't able to find it yet. Is there maybe something missing or do I miss something?

Best regards

**Comment by DraperStudio** [comment]
It's from this package https://github.com/DraperStudio/Laravel-Database

I will need to update a few things for this package here and include the Database package again, I will try to do that within the next 2 or 3 days.

**Comment by DraperStudio** [comment]
I've added the database package dependency in v1.0.3 so you should be able to pull that in for now, more updates will be coming soon.
