### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Screpuh** [DraperStudio/Laravel-Rewardable#5]
Do you maybe have some example code? I'm finding it hard to figure out how to use the package.

**Comment by DraperStudio** [comment]
It's actually pretty straightforward. This is just some pseudo could of which you could use is for.

```php
if ($user->hasPosted(10)) {
    $user->grantCredit(Credit::find(1)); // e.g. 10 credits for posting 10 times in a forum or so
}

if ($user->getBalance() > 1000) {
    $user->grantBadge(Badge::find($id)); // e.g. Good Work Badge
}

if ($user->badges() > 5) {
    $user->grantRank(Rank::find($id)); // e.g. Apprentice Rank
}
```

**Comment by Screpuh** [comment]
Thanks, but when I try this I get an error. I have the following:

dd(User::findOrFail(Auth::id())->grantCredit(Credit::find(1)));

I get this error:

ErrorException in CreditRepository.php line 60:
array_merge(): Argument #1 is not an array

in CreditRepository.php line 60
at HandleExceptions->handleError('2', 'array_merge(): Argument #1 is not an array', '.../vendor/draperstudio/laravel-rewardable/src/Repositories/CreditRepository.php', '60', array('credit' => object(Credit)))
at array_merge(object(Credit), array('credit_type_id' => '1', 'awarded_at' => object(Carbon))) in CreditRepository.php line 60
at CreditRepository->grantCredit(object(Credit)) in Creditable.php line 42
at User->grantCredit(object(Credit)) in routes.php line 72

I use the following database settings:
CreditType::create(['name' => 'New User']);

$credit = new Credit;
$credit->credit_type_id = 1;
$credit->name = 'new-user';
$credit->amount = 10;
$creditable_id = 1;

**Comment by DraperStudio** [comment]
I will take a look at this in the evening and let you know then or tomorrow.

**Comment by Screpuh** [comment]
Thanks, appreciate it.

**Comment by DraperStudio** [comment]
I found the issue, pretty silly one. In the `grantCredit` in `CreditRepository` I need to check if the Credit is an instance of `Credit` or an array.

**Not working**
```php
$credit = new Credit(array_merge(array_except($credit, ['type'])
```

**Working**
```php
$credit = new Credit(array_merge(array_except($credit->toArray(), ['type'])
```

I am currently reorganizing the package and probably will enforce that the Credit/Badge/Rank passed to the `grant*` methods either implement a certain interface or are instances of the Credit/Badge/Rank Eloquent Models.

**Comment by DraperStudio** [comment]
The next version will make it possible to pass in `one-time-credits` or credits from the database which are Eloquent models.

**A static credit which is created on-the-fly and not stored or retrieved from the database, just awarded**
```php
$user->grantCredit(new StaticCredit('name', 10, CreditType::first()));
```

**A credit that is stored and retrieved from the database**
```php
$user->grantCredit(Credit::find(1));
```

**Comment by Screpuh** [comment]
Thanks! Much appreciated. Really like this Package :)

**Comment by DraperStudio** [comment]
Closed for now, update should come within the next few days.
