### ISSUE TITLE
Example: How to List Rewards by Model

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Rewardable#6]
This may be due to my n00bness to traits in laravel but...
How do I list Models by Rewards?
(I have a similar question for most of your works, thanks in advance)

**Comment by DraperStudio** [comment]
What do you mean by rewards? Do you have an example/pseudo-code of what you would like todo?

**Comment by maximusblade** [comment]
I would like to list all users with "Rewards"  or "Credits" 
I would like to do something like this ?

$users_with_badges = User::GetUsersByBadge($badge_id);

**Comment by DraperStudio** [comment]
Not possible at the moment but I might add this since I am working on some updates for this package at the moment.

Anything else you would need?

**Comment by maximusblade** [comment]
First of all, Great work! (for this and you other work)
Allowing a user to list by the various traits would be incredibly useful.
The same goes for the other packages?

I'm glad I came across this.

**Comment by DraperStudio** [comment]
Please open issues on the other packages where you would like to have new functions and what they should do so I have a better overview. Thanks.

**Comment by maximusblade** [comment]
Will do ;)

**Comment by Pandahisham** [comment]
Sir , you are a life saver ! Your packages just made an intranet app dirt easy ! Can you please consider building an event/appointment package with recurrent event and export/import of ical files . dreadfully in need of one .
